forge "https://forgeapi.puppetlabs.com"

mod 'saz/timezone', '3.1.1'
mod 'mayflower/php', '3.2.2'
mod 'puppetlabs/inifile', '1.1.4'
mod 'jfryman/nginx', '0.2.6'
mod 'puppetlabs/firewall', '1.6.0'
mod 'puppetlabs/apache', '1.5.0'
mod 'puppetlabs/mysql', '3.4.0'
